language: java
jdk:
    - openjdk6
install:
    - ant
    - npm install
script:
    - ./tests/suite.sh
    - npm test
notifications:
    email:
        - davglass@gmail.com
        - davglass@yahoo-inc.com
